"""Add date column to dashboard_stats

Revision ID: 71f3e381a97f
Revises: a485d84a022b
Create Date: 2025-04-05 04:09:53.912075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f3e381a97f'
down_revision: Union[str, None] = 'a485d84a022b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_stats', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('dashboard_stats', sa.Column('total_faces_detected', sa.Integer(), nullable=True))
    op.add_column('dashboard_stats', sa.Column('total_login_attempts', sa.Integer(), nullable=True))
    op.drop_column('dashboard_stats', 'login_attempts')
    op.drop_column('dashboard_stats', 'total_faces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_stats', sa.Column('total_faces', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dashboard_stats', sa.Column('login_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('dashboard_stats', 'total_login_attempts')
    op.drop_column('dashboard_stats', 'total_faces_detected')
    op.drop_column('dashboard_stats', 'date')
    # ### end Alembic commands ###
